services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: dynamic_Pdf_Db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khayal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-pdf-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dynamic_Pdf_Db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: khayal
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: